# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y python-pip zsh
          - pip install -r requirements.txt
          - ./pyerect test

  bookmarks:
    release-*:
      - step:
         script:
           - apt-get update && apt-get install -y python-pip zsh
           - pip install -r requirements.txt
           - ./pyerect test upload

  custom:  # manually triggered
    manual:
      - step:
          script:
            - apt-get update && apt-get install -y python-pip zsh
            - pip install -r requirements.txt
            - ./pyerect test

    package:
      - step:
          script:
            - apt-get update && apt-get install -y python-pip zsh
            - pip install -r requirements.txt
            - ./pyerect upload
