# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.

pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - ./pyerect test

  custom:  # manually triggered
    - step:
        script:
          - pip install -r requirements.txt
          - ./pyerect test
